// Package codegen provides Walens-specific Go-Jet generation tooling,
// metadata mapping helpers, and post-processing utilities.
//
// This package centralizes the mapping rules that govern how database
// columns are translated into Go types in generated model code:
//   - UUID mapping for id and *_id columns
//   - Unix-millisecond timestamp mapping for named timestamp columns
//   - Duration mapping for *_ms columns
//   - Boolean mapping for is_* columns
//   - RawJSON mapping for json_* columns
//   - Documentation tag generation for doc:"..." struct tags
package codegen

import (
	"fmt"
	"strings"
	"unicode"
)

// =============================================================================
// Column classification constants
// =============================================================================

const (
	// TypeUUID marks columns that should use dbtypes.UUID.
	TypeUUID = "UUID"
	// TypeBoolInt marks columns that should use dbtypes.BoolInt.
	TypeBoolInt = "BoolInt"
	// TypeUnixMilliTime marks columns that should use dbtypes.UnixMilliTime.
	TypeUnixMilliTime = "UnixMilliTime"
	// TypeUnixMilliDuration marks columns that should use dbtypes.UnixMilliDuration.
	TypeUnixMilliDuration = "UnixMilliDuration"
	// TypeRawJSON marks columns that should use dbtypes.RawJSON.
	TypeRawJSON = "RawJSON"
	// TypeString is for regular String columns.
	TypeString = "string"
	// TypeInt64 is for regular integer columns.
	TypeInt64 = "int64"
	// TypeFloat64 is for real/float columns.
	TypeFloat64 = "float64"
	// TypeBytes is for blob columns.
	TypeBytes = "[]byte"
)

// =============================================================================
// Known column name sets (explicit, not guessed)
// =============================================================================

// knownTimestampColumns is the authoritative set of column names that are
// Unix-millisecond timestamps. This set is intentionally explicit rather
// than derived from suffixes to avoid misclassification.
//
// Only columns in this map (and INTEGER type) will be treated as timestamps.
var knownTimestampColumns = map[string]bool{
	"created_at":  true, // Standard audit timestamp
	"updated_at":  true, // Standard audit timestamp
	"started_at":  true, // Job start time
	"finished_at": true, // Job finish time
	"run_after":   true, // Scheduled job execution time
	"deleted_at":  true, // Soft delete timestamp
	"archived_at": true, // Archive timestamp
	"last_run_at": true, // Last scheduled run time
	"next_run_at": true, // Next scheduled run time
	"claimed_at":  true, // Job claiming timestamp
	"locked_at":   true, // Row lock timestamp
}

// knownDurationColumns is the authoritative set of column names that are
// Unix-millisecond durations. Only columns ending with _ms AND in this set
// (with INTEGER type) will be treated as durations.
var knownDurationColumns = map[string]bool{
	"duration_ms":   true, // Job execution duration
	"processing_ms": true, // Processing time
	"elapsed_ms":    true, // Elapsed time
	"latency_ms":    true, // Network/API latency
	"timeout_ms":    true, // Timeout setting
}

// knownJSONColumns is the authoritative set of column names that store
// raw JSON data. Only these names (with TEXT type) will be treated as JSON.
var knownJSONColumns = map[string]bool{
	"params":      true, // Source configuration params
	"json_meta":   true, // Image metadata as JSON
	"json_input":  true, // Job input as JSON
	"json_result": true, // Job result as JSON
	"metadata":    true, // Generic metadata
	"config":      true, // Configuration data
	"settings":    true, // Settings data
	"payload":     true, // Request/response payload
}

// =============================================================================
// Column classification predicates
// =============================================================================

// IsUUIDColumn returns true if the column should use dbtypes.UUID.
//
// Classification rules:
//   - Column must be a text-based type (TEXT, VARCHAR, CHAR)
//   - Column name must be exactly "id" or end with "_id"
//   - Column name must NOT end with "_identifier" (those are external IDs)
//
// Internal IDs use UUIDv7 generated by the application.
// External/source-owned identifiers use "*_identifier" naming.
func IsUUIDColumn(columnName string, dbType string) bool {
	dbType = strings.ToLower(dbType)
	lower := strings.ToLower(columnName)

	// Must be text type
	if dbType != "text" && dbType != "varchar" && dbType != "char" && dbType != "character varying" {
		return false
	}

	// Must be "id" or end with "_id" but NOT "_identifier"
	if lower == "id" || strings.HasSuffix(lower, "_id") {
		// Explicitly exclude identifier columns (external IDs)
		if strings.HasSuffix(lower, "_identifier") {
			return false
		}
		return true
	}

	return false
}

// IsUnixMilliTimestampColumn returns true if the column should use dbtypes.UnixMilliTime.
//
// Classification rules:
//   - Column must be an integer type (INTEGER, INT, INT64)
//   - Column name must be in the explicit knownTimestampColumns set
//
// This function intentionally does NOT use suffix matching like "_at" because
// that would misclassify columns like "cost_at" or "rate_at" as timestamps.
func IsUnixMilliTimestampColumn(columnName string, dbType string) bool {
	dbType = strings.ToLower(dbType)
	lower := strings.ToLower(columnName)

	// Must be integer type
	if dbType != "integer" && dbType != "int" && dbType != "int64" && dbType != "int32" {
		return false
	}

	// Must be in explicit known set
	return knownTimestampColumns[lower]
}

// IsDurationColumn returns true if the column should use dbtypes.UnixMilliDuration.
//
// Classification rules:
//   - Column must be an integer type (INTEGER, INT, INT64)
//   - Column name must end with "_ms" AND be in knownDurationColumns set
//
// This requires explicit membership rather than just suffix matching to avoid
// misclassifying arbitrary integer columns like "count_ms" or "max_ms".
func IsDurationColumn(columnName string, dbType string) bool {
	dbType = strings.ToLower(dbType)
	lower := strings.ToLower(columnName)

	// Must be integer type
	if dbType != "integer" && dbType != "int" && dbType != "int64" && dbType != "int32" {
		return false
	}

	// Must end with _ms AND be in known set
	if !strings.HasSuffix(lower, "_ms") {
		return false
	}
	return knownDurationColumns[lower]
}

// IsBoolIntColumn returns true if the column should use dbtypes.BoolInt.
//
// Classification rules:
//   - Column must be an integer type (INTEGER, INT, INT64)
//   - Column name must start with "is_"
func IsBoolIntColumn(columnName string, dbType string) bool {
	dbType = strings.ToLower(dbType)
	lower := strings.ToLower(columnName)

	// Must be integer type
	if dbType != "integer" && dbType != "int" && dbType != "int64" && dbType != "int32" {
		return false
	}

	// Must start with "is_"
	return strings.HasPrefix(lower, "is_")
}

// IsRawJSONColumn returns true if the column should use dbtypes.RawJSON.
//
// Classification rules:
//   - Column must be a text type (TEXT, VARCHAR, CHAR)
//   - Column name must be in the explicit knownJSONColumns set OR start with "json_"
func IsRawJSONColumn(columnName string, dbType string) bool {
	dbType = strings.ToLower(dbType)
	lower := strings.ToLower(columnName)

	// Must be text type
	if dbType != "text" && dbType != "varchar" && dbType != "char" && dbType != "character varying" {
		return false
	}

	// Must be in known set OR start with json_
	if knownJSONColumns[lower] {
		return true
	}
	return strings.HasPrefix(lower, "json_")
}

// ClassifyColumn determines the appropriate Go type for a database column.
func ClassifyColumn(columnName string, dbType string) (goType string, nullable bool) {
	dbType = strings.ToLower(dbType)

	// Order matters: most specific first
	if IsUUIDColumn(columnName, dbType) {
		return TypeUUID, false
	}
	if IsUnixMilliTimestampColumn(columnName, dbType) {
		return TypeUnixMilliTime, false
	}
	if IsDurationColumn(columnName, dbType) {
		return TypeUnixMilliDuration, false
	}
	if IsBoolIntColumn(columnName, dbType) {
		return TypeBoolInt, false
	}
	if IsRawJSONColumn(columnName, dbType) {
		return TypeRawJSON, false
	}

	// Default type mapping based on DB type
	switch dbType {
	case "text", "varchar", "char", "character varying":
		return TypeString, false
	case "integer", "int", "int64", "int32", "bigint", "smallint", "tinyint":
		return TypeInt64, false
	case "real", "float", "double", "numeric", "decimal":
		return TypeFloat64, false
	case "blob", "binary", "varbinary":
		return TypeBytes, false
	default:
		// Default to string for unknown types
		return TypeString, false
	}
}

// ClassifyColumnByName classifies a column based only on its name.
// This is used when we don't have the DB type information (e.g., from generated models).
// It uses the column name classification predicates which don't need DB type.
func ClassifyColumnByName(columnName string) (goType string, nullable bool) {
	lower := strings.ToLower(columnName)

	// Order matters: most specific first
	if lower == "id" || strings.HasSuffix(lower, "_id") {
		if !strings.HasSuffix(lower, "_identifier") {
			return TypeUUID, false
		}
	}
	if knownTimestampColumns[lower] {
		return TypeUnixMilliTime, false
	}
	if strings.HasSuffix(lower, "_ms") && knownDurationColumns[lower] {
		return TypeUnixMilliDuration, false
	}
	if strings.HasPrefix(lower, "is_") {
		return TypeBoolInt, false
	}
	if knownJSONColumns[lower] || strings.HasPrefix(lower, "json_") {
		return TypeRawJSON, false
	}

	// Default to string for unknown
	return TypeString, false
}

// =============================================================================
// Column metadata and documentation
// =============================================================================

// ColumnDoc holds documentation metadata for a column.
// This is the authoritative source for doc tags - not SQLite comments.
type ColumnDoc struct {
	// Description is the human-readable description of the column.
	Description string
	// IsRequired indicates this column is required (NOT NULL without default).
	IsRequired bool
}

// TableDoc holds documentation for all columns in a table.
type TableDoc struct {
	// TableName is the SQL table name.
	TableName string
	// Description is the table's human-readable description.
	Description string
	// Columns maps column name to its documentation.
	Columns map[string]ColumnDoc
}

// WalensSchemaDocs is the authoritative documentation metadata for all
// Walens business schema columns. This mapping must be kept in sync with
// the actual migrations.
//
// Each table and column must have an entry here. Missing documentation
// for business columns should cause validation failures.
var WalensSchemaDocs = map[string]TableDoc{
	"configs": {
		TableName:   "configs",
		Description: "Application configuration persisted in the database",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Primary key, always 1 for single-row config",
				IsRequired:  true,
			},
			"value": {
				Description: "Full serialized application config as JSON",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"devices": {
		TableName:   "devices",
		Description: "User-managed wallpaper consumer device",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique device identifier (UUIDv7)",
				IsRequired:  true,
			},
			"name": {
				Description: "Human-readable device name",
				IsRequired:  true,
			},
			"slug": {
				Description: "URL-safe device identifier for paths",
				IsRequired:  true,
			},
			"screen_width": {
				Description: "Device screen width in pixels",
				IsRequired:  true,
			},
			"screen_height": {
				Description: "Device screen height in pixels",
				IsRequired:  true,
			},
			"min_image_width": {
				Description: "Minimum image width filter in pixels (0 = no limit)",
				IsRequired:  true,
			},
			"max_image_width": {
				Description: "Maximum image width filter in pixels (0 = no limit)",
				IsRequired:  true,
			},
			"min_image_height": {
				Description: "Minimum image height filter in pixels (0 = no limit)",
				IsRequired:  true,
			},
			"max_image_height": {
				Description: "Maximum image height filter in pixels (0 = no limit)",
				IsRequired:  true,
			},
			"min_filesize": {
				Description: "Minimum file size filter in bytes (0 = no limit)",
				IsRequired:  true,
			},
			"max_filesize": {
				Description: "Maximum file size filter in bytes (0 = no limit)",
				IsRequired:  true,
			},
			"is_adult_allowed": {
				Description: "Whether adult content is allowed for this device",
				IsRequired:  true,
			},
			"is_enabled": {
				Description: "Whether the device is active and receiving wallpapers",
				IsRequired:  true,
			},
			"aspect_ratio_tolerance": {
				Description: "Absolute aspect ratio tolerance for matching wallpapers",
				IsRequired:  true,
			},
			"created_at": {
				Description: "Device creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"sources": {
		TableName:   "sources",
		Description: "Configured source row representing a wallpaper source",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique source identifier (UUIDv7)",
				IsRequired:  true,
			},
			"name": {
				Description: "Unique human-readable source name",
				IsRequired:  true,
			},
			"source_type": {
				Description: "Registered source implementation name (e.g., booru, reddit)",
				IsRequired:  true,
			},
			"params": {
				Description: "Source-specific configuration as JSON",
				IsRequired:  true,
			},
			"lookup_count": {
				Description: "Upstream lookup budget per run (0 = use source default)",
				IsRequired:  true,
			},
			"is_enabled": {
				Description: "Whether this source is active",
				IsRequired:  true,
			},
			"created_at": {
				Description: "Source creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"source_schedules": {
		TableName:   "source_schedules",
		Description: "Cron schedule for a source row",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique schedule identifier (UUIDv7)",
				IsRequired:  true,
			},
			"source_id": {
				Description: "Reference to parent source",
				IsRequired:  true,
			},
			"cron_expr": {
				Description: "Five-field cron expression (minute, hour, day, month, weekday)",
				IsRequired:  true,
			},
			"is_enabled": {
				Description: "Whether this schedule is active",
				IsRequired:  true,
			},
			"created_at": {
				Description: "Schedule creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"device_source_subscriptions": {
		TableName:   "device_source_subscriptions",
		Description: "Connects a device to a source for wallpaper targeting",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique subscription identifier (UUIDv7)",
				IsRequired:  true,
			},
			"device_id": {
				Description: "Reference to subscribed device",
				IsRequired:  true,
			},
			"source_id": {
				Description: "Reference to subscribed source",
				IsRequired:  true,
			},
			"is_enabled": {
				Description: "Whether this subscription is active",
				IsRequired:  true,
			},
			"created_at": {
				Description: "Subscription creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"images": {
		TableName:   "images",
		Description: "Canonical downloaded image record",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique image identifier (UUIDv7)",
				IsRequired:  true,
			},
			"source_id": {
				Description: "Reference to source this image came from",
				IsRequired:  false,
			},
			"unique_identifier": {
				Description: "Source-provided unique identifier for dedupe",
				IsRequired:  true,
			},
			"source_type": {
				Description: "Source implementation type name",
				IsRequired:  true,
			},
			"original_filename": {
				Description: "Original filename from source",
				IsRequired:  false,
			},
			"preview_url": {
				Description: "Low-resolution preview URL",
				IsRequired:  false,
			},
			"origin_url": {
				Description: "Original source URL for the image",
				IsRequired:  false,
			},
			"source_item_identifier": {
				Description: "External source item/post identifier",
				IsRequired:  false,
			},
			"original_identifier": {
				Description: "External original/source identifier",
				IsRequired:  false,
			},
			"uploader": {
				Description: "Uploader/artist name from source",
				IsRequired:  false,
			},
			"artist": {
				Description: "Artist/creator name from source",
				IsRequired:  false,
			},
			"mime_type": {
				Description: "Image MIME type",
				IsRequired:  false,
			},
			"file_size_bytes": {
				Description: "File size in bytes",
				IsRequired:  false,
			},
			"width": {
				Description: "Image width in pixels",
				IsRequired:  false,
			},
			"height": {
				Description: "Image height in pixels",
				IsRequired:  false,
			},
			"aspect_ratio": {
				Description: "Image aspect ratio (width/height)",
				IsRequired:  false,
			},
			"is_adult": {
				Description: "Whether the image contains adult content",
				IsRequired:  true,
			},
			"is_favorite": {
				Description: "Whether the user marked this as favorite",
				IsRequired:  true,
			},
			"json_meta": {
				Description: "Additional image metadata as JSON",
				IsRequired:  true,
			},
			"created_at": {
				Description: "Image creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"tags": {
		TableName:   "tags",
		Description: "Normalized image tag",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique tag identifier (UUIDv7)",
				IsRequired:  true,
			},
			"name": {
				Description: "Original tag name",
				IsRequired:  true,
			},
			"normalized_name": {
				Description: "Lowercase trimmed canonical tag name for dedupe",
				IsRequired:  true,
			},
			"created_at": {
				Description: "Tag creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"image_tags": {
		TableName:   "image_tags",
		Description: "Join table between images and tags",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique join record identifier (UUIDv7)",
				IsRequired:  true,
			},
			"image_id": {
				Description: "Reference to image",
				IsRequired:  true,
			},
			"tag_id": {
				Description: "Reference to tag",
				IsRequired:  true,
			},
			"created_at": {
				Description: "Tag assignment timestamp",
				IsRequired:  true,
			},
		},
	},
	"image_assignments": {
		TableName:   "image_assignments",
		Description: "Tracks which devices an image has been assigned to",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique assignment identifier (UUIDv7)",
				IsRequired:  true,
			},
			"image_id": {
				Description: "Reference to assigned image",
				IsRequired:  true,
			},
			"device_id": {
				Description: "Reference to target device",
				IsRequired:  true,
			},
			"created_at": {
				Description: "Assignment creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"image_locations": {
		TableName:   "image_locations",
		Description: "Tracks concrete file paths on disk for images",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique location identifier (UUIDv7)",
				IsRequired:  true,
			},
			"image_id": {
				Description: "Reference to image",
				IsRequired:  true,
			},
			"device_id": {
				Description: "Reference to device this path is for",
				IsRequired:  true,
			},
			"path": {
				Description: "Absolute filesystem path to the image file",
				IsRequired:  true,
			},
			"storage_kind": {
				Description: "Storage type: canonical, hardlink, or copy",
				IsRequired:  true,
			},
			"is_primary": {
				Description: "Whether this is the primary device location",
				IsRequired:  true,
			},
			"is_active": {
				Description: "Whether this location is currently active",
				IsRequired:  true,
			},
			"created_at": {
				Description: "Location creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"image_thumbnails": {
		TableName:   "image_thumbnails",
		Description: "Generated thumbnail derived from a downloaded image",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique thumbnail identifier (UUIDv7)",
				IsRequired:  true,
			},
			"image_id": {
				Description: "Reference to source image",
				IsRequired:  true,
			},
			"path": {
				Description: "Absolute filesystem path to the thumbnail",
				IsRequired:  true,
			},
			"width": {
				Description: "Thumbnail width in pixels",
				IsRequired:  true,
			},
			"height": {
				Description: "Thumbnail height in pixels",
				IsRequired:  true,
			},
			"file_size_bytes": {
				Description: "Thumbnail file size in bytes",
				IsRequired:  false,
			},
			"created_at": {
				Description: "Thumbnail creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"image_blacklists": {
		TableName:   "image_blacklists",
		Description: "Blocks download of unwanted images by source+identifier",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique blacklist entry identifier (UUIDv7)",
				IsRequired:  true,
			},
			"source_id": {
				Description: "Reference to source this blacklist applies to",
				IsRequired:  true,
			},
			"unique_identifier": {
				Description: "Source-specific image identifier to block",
				IsRequired:  true,
			},
			"reason": {
				Description: "Human-readable reason for blacklisting",
				IsRequired:  false,
			},
			"created_at": {
				Description: "Blacklist entry creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
	"jobs": {
		TableName:   "jobs",
		Description: "Persisted execution record for source sync/download jobs",
		Columns: map[string]ColumnDoc{
			"id": {
				Description: "Unique job identifier (UUIDv7)",
				IsRequired:  true,
			},
			"job_type": {
				Description: "Job type: source_sync or source_download",
				IsRequired:  true,
			},
			"source_id": {
				Description: "Reference to source this job is for",
				IsRequired:  false,
			},
			"source_name": {
				Description: "Denormalized source name for job history",
				IsRequired:  false,
			},
			"source_type": {
				Description: "Denormalized source type for job history",
				IsRequired:  false,
			},
			"status": {
				Description: "Job status: queued, running, succeeded, failed, cancelled",
				IsRequired:  true,
			},
			"trigger_kind": {
				Description: "What triggered this job: manual, schedule, or recovery",
				IsRequired:  true,
			},
			"run_after": {
				Description: "When the job should run (Unix milliseconds)",
				IsRequired:  true,
			},
			"started_at": {
				Description: "When the job actually started (Unix milliseconds)",
				IsRequired:  false,
			},
			"finished_at": {
				Description: "When the job finished (Unix milliseconds)",
				IsRequired:  false,
			},
			"duration_ms": {
				Description: "Job execution duration in milliseconds",
				IsRequired:  false,
			},
			"requested_image_count": {
				Description: "How many images were requested to fetch",
				IsRequired:  true,
			},
			"downloaded_image_count": {
				Description: "How many images were actually downloaded",
				IsRequired:  true,
			},
			"reused_image_count": {
				Description: "How many images were reused from existing files",
				IsRequired:  true,
			},
			"hardlinked_image_count": {
				Description: "How many images were hard-linked to new device paths",
				IsRequired:  true,
			},
			"copied_image_count": {
				Description: "How many images were copied as fallback",
				IsRequired:  true,
			},
			"stored_image_count": {
				Description: "How many image records were persisted",
				IsRequired:  true,
			},
			"skipped_image_count": {
				Description: "How many images were skipped during processing",
				IsRequired:  true,
			},
			"message": {
				Description: "Informational message about the job result",
				IsRequired:  false,
			},
			"error_message": {
				Description: "Error message if the job failed",
				IsRequired:  false,
			},
			"json_input": {
				Description: "Job input parameters as JSON",
				IsRequired:  true,
			},
			"json_result": {
				Description: "Job result metadata as JSON",
				IsRequired:  true,
			},
			"created_at": {
				Description: "Job creation timestamp",
				IsRequired:  true,
			},
			"updated_at": {
				Description: "Last modification timestamp",
				IsRequired:  true,
			},
		},
	},
}

// GetColumnDoc returns the documentation for a specific column, or empty if not found.
func GetColumnDoc(tableName, columnName string) ColumnDoc {
	table, ok := WalensSchemaDocs[tableName]
	if !ok {
		return ColumnDoc{}
	}
	col, ok := table.Columns[columnName]
	if !ok {
		return ColumnDoc{}
	}
	return col
}

// GetTableDoc returns the documentation for a specific table, or nil if not found.
func GetTableDoc(tableName string) *TableDoc {
	table, ok := WalensSchemaDocs[tableName]
	if !ok {
		return nil
	}
	return &table
}

// ValidateSchemaDocs checks that documentation exists for all columns in a table.
// Returns an error listing any missing columns.
func ValidateSchemaDocs(tableName string, actualColumns []string) error {
	table, ok := WalensSchemaDocs[tableName]
	if !ok {
		return fmt.Errorf("table %q not found in schema docs", tableName)
	}

	var missing []string
	for _, col := range actualColumns {
		if _, ok := table.Columns[col]; !ok {
			missing = append(missing, col)
		}
	}

	if len(missing) > 0 {
		return fmt.Errorf("table %q is missing documentation for columns: %v", tableName, missing)
	}
	return nil
}

// DocTag builds a doc tag string from a description.
func DocTag(description string) string {
	if description == "" {
		return ""
	}
	// Escape double quotes for Go string literal
	escaped := strings.ReplaceAll(description, "\"", "\\\"")
	return fmt.Sprintf(`doc:"%s"`, escaped)
}

// BuildColumnTags builds the full struct tag string for a column.
func BuildColumnTags(jsonName string, goType string, col ColumnDoc) string {
	var parts []string
	if jsonName != "" {
		parts = append(parts, fmt.Sprintf("json:%q", jsonName))
	}
	if col.Description != "" {
		parts = append(parts, DocTag(col.Description))
	}
	return strings.Join(parts, " ")
}

// =============================================================================
// Schema validation helpers
// =============================================================================

// ValidateIdentifierName checks if a name follows Walens naming conventions.
// Internal IDs should be "id" or "*_id", external IDs should be "*_identifier".
func ValidateIdentifierName(name string) error {
	if name == "" {
		return fmt.Errorf("identifier name cannot be empty")
	}
	lower := strings.ToLower(name)

	// Check for external ID misuse (should be *_identifier, not *_id)
	if strings.HasSuffix(lower, "_id") && !strings.HasSuffix(lower, "_identifier") {
		// This might be an external ID that should use *_identifier instead
		// Allow if it looks like a standard internal ID pattern
		standardInternalIDs := map[string]bool{
			"id":          true,
			"source_id":   true,
			"device_id":   true,
			"image_id":    true,
			"tag_id":      true,
			"job_id":      true,
			"config_id":   true,
			"schedule_id": true,
		}
		if !standardInternalIDs[lower] {
			return fmt.Errorf("column %q ends with _id but may be an external identifier; use _identifier for external/source-owned IDs", name)
		}
	}

	return nil
}

// =============================================================================
// Generator-driven model field helpers
// =============================================================================

// ClassifyColumnForGenerator classifies a column for model generation using
// Go-Jet metadata. This combines the column classification with nullable handling.
// It prefers using the provided dbType if available, otherwise falls back to
// name-based classification.
func ClassifyColumnForGenerator(tableName string, columnName string, isNullable bool, dbType string) (goType string, wrappedType string, needsPointer bool) {
	if tableName == "configs" && columnName == "value" {
		goType = TypeRawJSON
		wrappedType = ToGoType(goType)
		needsPointer = isNullable
		return goType, wrappedType, needsPointer
	}

	// If dbType is provided and not empty, use it for classification
	if dbType != "" {
		goType, _ = ClassifyColumn(columnName, dbType)
	} else {
		// Fall back to name-based classification
		goType, _ = ClassifyColumnByName(columnName)
	}
	wrappedType = ToGoType(goType)
	needsPointer = isNullable
	return goType, wrappedType, needsPointer
}

// =============================================================================
// String utilities
// =============================================================================

// ToGoName converts a SQL column name to a Go field name.
// Example: created_at -> CreatedAt, is_enabled -> IsEnabled, source_id -> SourceID
func ToGoName(sqlName string) string {
	parts := strings.Split(sqlName, "_")
	for i, part := range parts {
		if len(part) == 0 {
			continue
		}
		upper := strings.ToUpper(part)
		// Handle common Go acronyms
		switch upper {
		case "ID":
			parts[i] = "ID"
			continue
		case "URL", "URI", "URN", "UUID":
			parts[i] = upper
			continue
		case "IO", "OS", "HTTP", "TCP", "UDP", "SQL":
			parts[i] = upper
			continue
		}
		// Capitalize first letter
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		parts[i] = string(runes)
	}
	return strings.Join(parts, "")
}

// ToGoType converts a Walens type constant to actual Go type name.
func ToGoType(typeConst string) string {
	switch typeConst {
	case TypeUUID:
		return "dbtypes.UUID"
	case TypeBoolInt:
		return "dbtypes.BoolInt"
	case TypeUnixMilliTime:
		return "dbtypes.UnixMilliTime"
	case TypeUnixMilliDuration:
		return "dbtypes.UnixMilliDuration"
	case TypeRawJSON:
		return "dbtypes.RawJSON"
	case TypeString:
		return "string"
	case TypeInt64:
		return "int64"
	case TypeFloat64:
		return "float64"
	case TypeBytes:
		return "[]byte"
	default:
		return "any"
	}
}
